fix(typing): limit supported data types to subclasses of `np.generic`
caniko/pydantic-numpy pull request #24
Opened 2023-12-29 10:38 UTC by futurwasfree

test: remove few `pyright: ignore` instructions where we previously failed for common Python types
chore: bump PATCH

---
Hello again! :)
Just a draft to start discussion as always. 
I think we've touched upon these `pyright` warnings that I've had too silence in a previous PR since deducted type was too wide and generic.
This commit fixes it and limits accepted `data_type` to subclasses of `np.generic` only. 
Thanks for looking into and let me know what you think!

2023-12-30 16:36 UTC, caniko requested changes
Thanks for the PR, I took the liberty to review the code. LGTM :100:

2023-12-30 16:36 UTC, caniko commented on pydantic_numpy/helper/typing.py
> +SupportedDTypes = Type[np.generic]
```suggestion
SupportedDTypes = type[np.generic]
```

You can also remove the imports of `typing.Type`.

2023-12-30 16:36 UTC, caniko commented on pydantic_numpy/helper/annotation.py
> +                np.dtype[data_type] if _data_type_resolver(data_type) else data_type,  # type: ignore[valid-type]
Could you elaborate on this change?

2023-12-31 09:16 UTC, futurewasfree commented on pydantic_numpy/helper/typing.py
> +SupportedDTypes = Type[np.generic]
great tip! and it should work just fine in Python 3.9.
just did your change.

2023-12-31 09:21 UTC, futurewasfree commented on pydantic_numpy/helper/annotation.py
> +                np.dtype[data_type] if _data_type_resolver(data_type) else data_type,  # type: ignore[valid-type]
That's a bit tricky one. mypy was unhappy:
```
pydantic_numpy/helper/annotation.py:119: error: Variable "data_type" is not valid as a type  [valid-type]
pydantic_numpy/helper/annotation.py:119: note: Error code "valid-type" not covered by "type: ignore" comment
pydantic_numpy/helper/annotation.py:119: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```
Most likely since we've introduced `Optional`[here and mypy doesn't respect `None` as the type.
Very little change with how it was before: `data_type: DTypeLike = None`, but it's complaining now.

Not sure yet how to fix it properly. Will it accept `NoneType` in some form instead?

2024-01-01 12:48 UTC, futurewasfree commented on pydantic_numpy/helper/annotation.py
> +                np.dtype[data_type] if _data_type_resolver(data_type) else data_type,  # type: ignore[valid-type]
actually I was wrong and it's not related to `NoneType` here. Made a minimal example to reproduce:
```
import numpy as np


def main(data_type: type[np.uint32]):
    a: np.dtype[data_type]
    b: np.dtype[np.uint32]


main(np.uint32)
```
gives me:
```
foobar.py:5: error: Variable "data_type" is not valid as a type
foobar.py:5: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```

at the same type `pyright` won't give any warning on this line.
might be related: https://github.com/python/mypy/issues/8897

should we keep it as is for now?

2024-01-01 17:15 UTC, caniko commented on pydantic_numpy/helper/annotation.py
> +                np.dtype[data_type] if _data_type_resolver(data_type) else data_type,  # type: ignore[valid-type]
You can't use numpy types directly with MyPy you need to wrap them in `np.dtype`.

I don't think there is any problem with this change, we move on.

2024-01-01 17:17 UTC, caniko approved these changes

2024-01-01 17:17 UTC, caniko commented
Is this ready to be merged?

2024-01-03 11:26 UTC, futurewasfree commented
> Is this ready to be merged?

I think so. Do I need to do something?

2024-01-03 11:46 UTC, merged

2024-01-03 12:09 UTC, futurewasfree commented
🥳 thanks again and happy new year!

2024-01-03 12:27 UTC, caniko commented
Happy new year! :partying_face: