(feat) custom serializer support
caniko/pydantic-numpy pull request #32
Opened 2024-02-11 16:18 UTC by futurwasfree

Draft and follow up on discussion started in https://github.com/caniko/pydantic-numpy/issues/28

2024-02-12 10:27 UTC, caniko requested changes
Thanks for the MR! Please reply to my comments, we are almost ready to merge!

2024-02-12 10:27 UTC, caniko commented on pydantic_numpy/helper/annotation.py
> +def _serialize_numpy_array_to_data_dict(array: np.ndarray) -> NumpyDataDict:
The function should be public since it is a frontend component.

```suggestion
def serialize_numpy_array_to_data_dict(array: np.ndarray) -> NumpyDataDict:
    """
    Serialize a NumPy array into a data dictionary format suitable for frontend display or processing.

    This function converts a given NumPy array into a dictionary format, which includes the data type 
    and the data itself. If the array contains datetime or timedelta objects, it converts them into integer 
    representations. Otherwise, the array is converted to a floating-point representation. This is particularly 
    useful for preparing NumPy array data for JSON serialization or similar use cases where NumPy's native 
    data types are not directly compatible.

    Note
    -------
    This function is intended for internal use within a package for handling specific serialization needs 
    of NumPy arrays for frontend applications or similar use cases. It should not be used as a general-purpose 
    serialization tool.

    Parameters
    -----------------
    array: np.ndarray
                  The NumPy array to be serialized. This can be a standard numerical array or an array 
                  of datetime/timedelta objects.

    Returns
    -----------
    NumpyDataDict
                   A dictionary with two keys: 'data_type', a string representing the data type of the array, 
                   and 'data', a list of values converted from the array. The conversion is to integer if the 
                   original data type is datetime or timedelta, and to float for other data types.
 
    Example
    ------------
    >>> array = np.array([1, 2, 3])
    >>> _serialize_numpy_array_to_data_dict(array)
    {'data_type': 'int64', 'data': [1.0, 2.0, 3.0]}
    """
```

2024-02-12 10:27 UTC, caniko commented on pydantic_numpy/helper/annotation.py
> +        serialize_numpy_array_to_json: Callable[[np.ndarray], Any] = _serialize_numpy_array_to_data_dict,
Why aren't we using `numpy.typing.ArrayLike`?

I always try to steer away from `Any`, can we use `typing.Iterable`?
```suggestion
        serialize_numpy_array_to_json: Callable[[npt.ArrayLike], Iterable] = _serialize_numpy_array_to_data_dict,
```

2024-02-12 12:34 UTC, futurewasfree commented
> Thanks for the MR! Please reply to my comments, we are almost ready to merge!

No, thank you for spending time on it and providing great feedback!
I've tried to apply your suggestions, but run into one problem with pyright:
```
/Users/sergei/Dev/pydantic-numpy/pydantic_numpy/helper/annotation.py
  /Users/sergei/Dev/pydantic-numpy/pydantic_numpy/helper/annotation.py:76:78 - error: Expression of type "(array: ndarray[Unknown, Unknown]) -> NumpyDataDict" cannot be assigned to parameter of type "(ArrayLike) -> Iterable[Unknown]"
    Type "(array: ndarray[Unknown, Unknown]) -> NumpyDataDict" cannot be assigned to type "(ArrayLike) -> Iterable[Unknown]"
      Parameter 1: type "ArrayLike" cannot be assigned to type "ndarray[Unknown, Unknown]"
        Type "ArrayLike" cannot be assigned to type "ndarray[Unknown, Unknown]"
          "bytes" is incompatible with "ndarray[Unknown, Unknown]" (reportGeneralTypeIssues)
```
and I think if we change input arg of `serialize_numpy_array_to_data_dict`  to `npt.ArrayLike` then we might not have all the ops defined on ArrayLike (no astype() or .dtype).       
          
FYI, from `pydantic-core`:
```
GeneralPlainNoInfoSerializerFunction = Callable[[Any], Any]
# (__input_value: Any, __info: FieldSerializationInfo) -> Any
GeneralPlainInfoSerializerFunction = Callable[[Any, SerializationInfo], Any]
# (__model: Any, __input_value: Any) -> Any
FieldPlainNoInfoSerializerFunction = Callable[[Any, Any], Any]
# (__model: Any, __input_value: Any, __info: FieldSerializationInfo) -> Any
FieldPlainInfoSerializerFunction = Callable[[Any, Any, FieldSerializationInfo], Any]
SerializerFunction = Union[
    GeneralPlainNoInfoSerializerFunction,
    GeneralPlainInfoSerializerFunction,
    FieldPlainNoInfoSerializerFunction,
    FieldPlainInfoSerializerFunction,
]
```
wildly untyped

2024-02-12 13:53 UTC, caniko commented on pydantic_numpy/helper/annotation.py
> +    -------
Are those my dash lines? :rofl:

Can we make them as long as the line above, it hurts to see this :stuck_out_tongue_winking_eye:

2024-02-12 14:23 UTC, futurewasfree commented on pydantic_numpy/helper/annotation.py
> +    -------
yeah, I just saw this cool feature that I could just apply your suggestions as commits, tried that. 
but I've aligned dashed with text above them.

2024-02-15 17:01 UTC, caniko commented
> wildly untyped

That makes sense because they are not beholden to the restrictions of what Numpy array can be, a Numpy array originates from an `Iterable` not matter what. While everything that may be serialized by a Pydantic model is `Any` - everything.

2024-02-15 17:01 UTC, caniko approved these changes

2024-02-15 17:02 UTC, caniko commented
I think we are ready to merge now. Thumbs up, and I proceed :smile_cat:

2024-02-17 16:14 UTC, futurewasfree commented
FYI, I've just pushed one more commit to squash last two into one.
Otherwise, we're ready, I believe

2024-02-19 16:12 UTC, caniko commented on pydantic_numpy/helper/annotation.py
> +    >>> _serialize_numpy_array_to_data_dict(array)
Update this

2024-02-19 16:14 UTC, caniko commented
I still haven't added a `CONTRIBUTOR.md` :see_no_evil:

The message should be:
`feat(validation): Custom serializer support`

2024-02-20 06:39 UTC, futurewasfree commented on pydantic_numpy/helper/annotation.py
> +    >>> _serialize_numpy_array_to_data_dict(array)
just did. line in example, right? nothing else?

2024-02-20 13:48 UTC, caniko commented on pydantic_numpy/helper/annotation.py
> +                cls.serialize_numpy_array_to_json, when_used="json"
`serialize_numpy_array_to_json` is an instance variable, and [not a class variable](https://github.com/caniko/pydantic-numpy/pull/32/files#diff-35ff13acb747a8fc01e3dbee84763b158eba7f8b0d7d43741e626f41ba734a32R78). You can fix this by wrapping the typing in `typing.ClassVar`.

2024-02-20 18:55 UTC, futurewasfree commented on pydantic_numpy/helper/annotation.py
> +                cls.serialize_numpy_array_to_json, when_used="json"
changed it. 
have you added `ClassVar` wrapping recently to other fields?
could be result of my old rebase..

2024-02-20 20:40 UTC, caniko commented on pydantic_numpy/helper/annotation.py
> +                cls.serialize_numpy_array_to_json, when_used="json"
No :man_shrugging:

2024-02-24 08:46 UTC, futurewasfree commented
Goood morning!
Could you merge it @caniko ? 
Even though you've approved, it's "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests"

2024-02-24 10:56 UTC, merged

2024-02-24 12:58 UTC, futurewasfree commented
I think I forgot to bump version :/

2024-02-24 15:15 UTC, caniko commented
I had some pending changes, no worries. Will bump on my PR, should be released in 10 minutes ;)